### ISSUE TITLE
Failed to get API tokens

### ISSUE THREAD

**Issue by skaboss241** [W1ndst0rm/Treillage#20]
Do you have any insight as to why I'm getting this error: treillage.exceptions.TreillageHTTPException: Failed to get API tokens
``
async def getnames():
    from treillage import Treillage
    from treillage.endpoints import get_contact_list

    async with Treillage(credentials_file="creds.yml") as tr:
        async for contact in get_contact_list(tr.conn, fields=['fullName', 'personId'], first_name='James'):
            print(contact['fullName'])

asyncio.run(getnames())
``

**Comment by moosmank** [comment]
My guess is that either your credentials are incorrect, or the key you were using has been removed.

**Comment by skaboss241** [comment]
Bummer. I'm not sure what the deal is then. The key should be good. Just
got it set up. Thanks for getting back to me though.

**Comment by W1ndst0rm** [comment]
It's either a problem with the credentials or the base URL. Check and make sure you're using the correct URL for your organization. The [Filevine API Docs](https://developer.filevine.io/docs/v2/ZG9jOjIyMTAyMTMx-base-url) explain how to format it if the default one won't work for your org.

**Comment by skaboss241** [comment]
That's it! Thanks. It's working now. I appreciate the help. :)
